services:
  # backend flask
  flask:
    build: ./web
    container_name: flask
    restart: always
    volumes:
      - ./volume/flask/dyn:/app/static/dyn
    environment: 
      - APP_NAME=FlaskAqi
      - TZ=Asia/Bangkok
      # - MAINTENANCE=True
    expose: 
      - "8080"
  # nginx infront of uwsgi
  nginx:
    build:
      context: https://github.com/bbilly1/aqi_monitor.git#master:nginx
    container_name: backend_nginx
    restart: always
    ports: 
      - "80:80"
    depends_on:
      - flask
  # backend postgres
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    volumes:
      - ./volume/postgres:/var/lib/postgresql/data/
    env_file:
      - ./env/postgres.env
    expose:
      - "5432"
